deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  npm_token: "$NPM_TOKEN"
  keep_history: true
  on:
    branch: master
language: node_js
cache:
  directories:
  - "~/.npm"
notifications:
  email: false
node_js:
- '10'
- '11'
- '8'
script:
- npm run test:prod && npm run build
after_success:
- npm run travis-deploy-once "npm run report-coverage"
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  run travis-deploy-once "npm run deploy-docs"; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm
  run travis-deploy-once "npm run sr"; fi
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: WPuJZvLNAyAfwu2gM89Y3t520/rnO5GK25Bf1WViJff5q893ZJ9e6dolFNw3MlTAhFPfC0JtJ4a2ymrIo+ExAb1KaqMB2wC8cNyJUWjJOp8TejyYdDb+CRBuo+GLAbBC0K8cFzadkQYcJH7cfczJiqiX1hjIkygFZgEdx94z9SMH9yded+WEHe7SOS7+WN3Eua3uQhPndLeqryr4BU8VErL2nRvPn7E8A88zbWfKipqpaDayf5iZWptjmIAo/iUaHr8ewlXdkxalyfJle0e+CSXzVhSrRRG0fTOw+qGAxvaQy2Bnvumi2RVRxhl/KU250iqSgUUN8Xox/L2rM7exjBdOa8FpfNf9knSG1seXu9SIWOp305DuBGjF0AUBpEkKV/gj0+5beqPSBo/H+54QuiHx74DjUqqy6axct0gZnRc6CMcY+xstmCe+Gws0ohMKwAjbklSyVwiWNmtKgC+qlI8VHrGLYjgLt1sbo8wP0FM31EY3tfvN39WLASBuSTLRmDK0/lWT5jZZp5GfYy9E4KXK4Yia8TQQEWpuSyZLU6++iBBi4jtCyRWl4VqbzvJJ/hOtMGxj6PEWi67AVpDjv/3ixdzIjMBVxjfUerraf2zgBPAcAxW0wGx1AbuIsJEuz7ho58i79CZYJxpPLCQ0GEs05V/Rbrac7GzG1nANgzU=
  - secure: M+qnyyddNkwR/XeavWxuB69GAYVVghPwEtICzLylgBtpoqieoJTgqUTcZZoBSFePE/YE1Vv2JexEARJQhjeJqc+GD4NX7kWwEdhHBEHwRNV08NcARJg1hrOHjseil8lIMi7HZGsrKKI+3TBTZmuN2WSjKQUEbCN2aRGB8gsUZ9WaSqba5O+y1GNg6n1bueddHIMNETFeTLMqCsMePIbckOHM/te1xYNk1A/iIUwEAPg5uzVL6kSMqsUSRfE3R3RqkuSH9eSTU/Va2V3VwN09rw9yLaWtkbGeWLIhZjFCJOk2sthfvM1LmU7n1ihU85s2Q5PWXHkZgQUadMLxTzVNvQdu2XkhepVjl0aE60tZdypc7KAs69KNKxK3n9SymhA6PmWBJ6oapGuJ/E3azFnf8pakb381SINR5XhvW7/IBbtIEKiHA5Ujkw2tYMQuSDPyrqd3R7MbL1Zzq4wHxZGH+b1sxxKljiKc4rHvcwrc0wD53cqH97mNOV3Fcd83hXfI9bQMvYcmTxOpNui6muaE3/MNWG7qEt9WabuC2a5Ix0B3nC6/rZkhu+By9L5NLpG1wP+E2X400Ti2yZaE2ZBdL/DUvTo9eBARbvvRYgczXfWHJMLTprbrTEKCuS43w0vq6qZ8kTUenP2ReZaXHckm5VI4NLQAjqiz93LlAO3aOMA=
